---
title: "Client Report - Exploring Names"
subtitle: "Unit 1 Task 1"
author: "Talmage Trebilcock"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## QUESTION 1

__What was the earliest year that the name ‘Felisha’ was used?__

The earliest year that the name 'Felisha' was used was 1964, there was a total of 20 babies named Felisha that

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q1
import polars as pl

df = pl.read_csv('names_year_csv.csv')

# This code filters by name so that the table only shows the name we are looking for. It will also only show the name, year, and total so that we can easily see all relevant data. Finally it sorts the data by year so that the earliest year will appear at the top of the table.
df.filter(
  pl.col('name') == 'Felisha'
).select(
  pl.col('name'),pl.col('year'),pl.col('Total')
).sort(
  pl.col('year').abs(),descending=False
).head(5)
```


## QUESTION 2

__What year had the most babies named 'David'? How many babies were named 'David' that year?__

The most babies born that were named David was in 1955 with a total of 86,389 babies named David in total that year.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q2
import polars as pl

df = pl.read_csv('names_year_csv.csv')

# This code filters by name so that the table only shows the name we are looking for. It will also only show the name, year, and total so that we can easily see all relevant data. Finally it sorts the total so the highest number appaers at the top of the chart making it easiest to figure out the year.
df.filter(
  pl.col('name') == 'David'
).select(
  pl.col('name'),pl.col('year'),pl.col('Total')
).sort(
  pl.col('Total').abs(),descending=True
).head(5)
```


## QUESTION 3

__What year did your name hit its peak? How many babies were named your name in that year?__

The year my name hit its peak was in 1931 and 1933 with a total of 25 babies named Talmage in each of those years.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q3
import polars as pl

df = pl.read_csv('names_year_csv.csv')

# This code filters by my name so that the table only shows the name we are looking for. It will also only show the name, year, and total so that we can easily see all relevant data. Finally it sorts the total so the highest number appaers at the top of the chart making it easiest to figure out the year.
df.filter(
  pl.col('name') == 'Talmage'
).select(
  pl.col('name'),pl.col('year'),pl.col('Total')
).sort(
  pl.col('Total').abs(),descending=True
).head(5)
```


## QUESTION 4

__In the most recent year, what was the most common female name in Utah?__ 

The most common female name in Utah in 2024 (the most recent year with data) was Olivia with a total of 215 babies named Olivia in that year within the state of Utah.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q5
import polars as pl

df = pl.read_csv('names_year_csv.csv')

# This code filters by year so that the table only shows the most recent data from 2024. It will also only show the name, year, and total for Utah so that we can easily see all relevant data. Finally it sorts the total for Utah so the highest number appaers at the top of the chart making it easiest to figure out which Girl's name was the most popular that year.
df.filter(
  pl.col('year') == 2024
).select(
  pl.col('name'),
  pl.col('year'),
  pl.col('UT')
).sort(
  pl.col('UT').abs(),descending=True
).head(7)
```


---