---
title: "Client Report - What's in a Name?"
subtitle: "Unit 1 Task 2"
author: "Talmage Trebilcock"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__How does your name at your birth year compare to its use historically? Your must provide a chart. The years labels on your charts should not include a comma.__ 

Historically, the name 'Talmage' has been declining in popularity in general. However, starting in the early 2000s, the name has seen quite the increase in popularity, which began to pick up during my brith year of 2003. Since then, the name has seeon continued increases in popularity with a recent decline in 2022 and 2023.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q1
import pandas as pd
from lets_plot import *

data = pd.read_csv('names_year_csv.csv')

LetsPlot.setup_html()

data = pd.read_csv('names_year_csv.csv')
filtered_data = data[data['name'] == 'Talmage']

(
    ggplot(data=filtered_data, mapping=aes(x='year', y='Total')) + 
    geom_point(size = 2) + 
    geom_line(size = 1) + 
    geom_smooth(method='lm') +
    scale_x_continuous(format='d') +
    labs(
        title="'Talmage' Usage Over Time",
        subtitle="Popularity of the 'Talmage' Baby Name",
        x='Year',
        y='Total Usage'
    ) + 
    theme_minimal()
)
```


## QUESTION 2

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

The name Tiana, while having it's highest peaks in the years 1995 and 1998, saw a great decrease in the early 2000s. But, once the movie "The Princess and the Frog" released in 2009, the name saw a huge spike in popularity in 2009 and 2010 before returning close to it's previous levels of popularity again about 3 years after the movie's release.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q2
import pandas as pd
from lets_plot import *

data = pd.read_csv('names_year_csv.csv')

LetsPlot.setup_html()

data = pd.read_csv('names_year_csv.csv')
filtered_data = data[data['name'] == 'Tiana']

(
    ggplot(data=filtered_data, mapping=aes(x='year', y='Total')) + 
    geom_point(size = 2) + 
    geom_line(size = 1) + 
    geom_smooth(method='lm') +
    scale_x_continuous(format='d') +
    labs(
        title="'Tiana' Usage Over Time",
        subtitle="Princess and the Frog influence on the 'Tiana' Baby Name",
        x='Year',
        y='Total Usage'
    ) + 
    theme_minimal()
)

```

## QUESTION 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__  

Almost each of the names have a increase in popularity in the 1940s and which each last until around the mid 1950s. Afer that, almost all of the names see a decrease in popularity, Mary seeing the largest decrease in popularity.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q3
import pandas as pd
from lets_plot import *

data = pd.read_csv('names_year_csv.csv')

LetsPlot.setup_html()

data = pd.read_csv('names_year_csv.csv')
names = ['Mary', 'Martha', 'Peter', 'Paul']
filtered_data = data[data['name'].isin(names) & data['year'].between(1920, 2000)]

(
    ggplot(data=filtered_data, mapping=aes(x='year', y='Total', color='name')) + 
    geom_point(size = 2) + 
    geom_line(size = 1) + 
    geom_smooth(method='lm') +
    scale_x_continuous(format='d') +
    labs(
        title="Christian Name Usage",
        subtitle="Popularity of Christian Baby Names (1920-2000)",
        x='Year',
        y='Total Usage',
        color='Name'
    ) + 
    theme_minimal()
)

```
<!-- Make sure at least one of your charts includes reference marks!! -->